/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package back_end;

/**
Leyva Perez Victor Manuel
Espinoza López Manuel Ángel
Carmona Barbosa Geovani Gael
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    private front_end.Cliente objCliente;
    private front_end.Conductor objConductor;
    private front_end.Administrador objAdministrador;
    private front_end.Vehiculo objVehiculo;
    private front_end.Tarifa objTarifa;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jButton9.addActionListener(this::jButton9ActionPerformed);
        jButton10.addActionListener(this::jButton10ActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Recepción de taxis");

        jLabel2.setText("CURP");

        jLabel3.setText("Nombres");

        jLabel4.setText("Apellidos");

        jLabel5.setText("Edad");

        jLabel6.setText("Telefono");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel3);

        jLabel7.setText("CURP");

        jLabel8.setText("Nom_completo");

        jLabel9.setText("Num_Licencia");

        jLabel10.setText("Placas");

        jLabel11.setText("Edad");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conductor", jPanel4);

        jLabel12.setText("CURP");

        jLabel13.setText("Nombres");

        jLabel14.setText("Apellidos");

        jLabel15.setText("Num_Empleado");

        jLabel16.setText("Turno");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Matutino", "Vespertino", "Noche" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("Administrador", jPanel5);

        jLabel17.setText("Placas");

        jLabel18.setText("Marca");

        jLabel19.setText("Modelo");

        jLabel20.setText("Año");

        jLabel21.setText("Color");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vehiculo", jPanel8);

        jLabel22.setText("Tipo_Servicio");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Basico(4)", "Estandar(5)", "Plus(6-9)" }));

        jLabel23.setText("Codigo");

        jLabel24.setText("Minutos");

        jLabel25.setText("Precio_K/M");

        jLabel26.setText("Costo");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tarifa", jPanel9);

        jButton1.setText("Crear");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton6.setText("Buscar");

        jButton7.setText("Mostrar");

        jButton8.setText("Actualizar");

        jButton9.setText("Borrar");

        jButton10.setText("Destruir");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel27.setText("Leyva Perez Victor Manuel, Espinoza López Manuel Ángel, Carmona Barbosa Geovani Gael");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        accionCrear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        accionBuscar();
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        accionMostrar();
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        accionActualizar();
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        accionBorrar();
    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
        accionDestruir();
    }

    private int getPestanaActiva() {
        return jTabbedPane1.getSelectedIndex();
    }

    private void accionCrear() {
        switch (getPestanaActiva()) {
            case 0 -> crearCliente();
            case 1 -> crearConductor();
            case 2 -> crearAdministrador();
            case 3 -> crearVehiculo();
            case 4 -> crearTarifa();
        }
    }

    private void accionBuscar() {
        switch (getPestanaActiva()) {
            case 0 -> buscarCliente();
            case 1 -> buscarConductor();
            case 2 -> buscarAdministrador();
            case 3 -> buscarVehiculo();
            case 4 -> buscarTarifa();
        }
    }

    private void accionMostrar() {
        switch (getPestanaActiva()) {
            case 0 -> mostrarCliente();
            case 1 -> mostrarConductor();
            case 2 -> mostrarAdministrador();
            case 3 -> mostrarVehiculo();
            case 4 -> mostrarTarifa();
        }
    }

    private void accionActualizar() {
        switch (getPestanaActiva()) {
            case 0 -> actualizarCliente();
            case 1 -> actualizarConductor();
            case 2 -> actualizarAdministrador();
            case 3 -> actualizarVehiculo();
            case 4 -> actualizarTarifa();
        }
    }

    private void accionBorrar() {
        switch (getPestanaActiva()) {
            case 0 -> borrarCliente();
            case 1 -> borrarConductor();
            case 2 -> borrarAdministrador();
            case 3 -> borrarVehiculo();
            case 4 -> borrarTarifa();
        }
    }

    private void accionDestruir() {
        switch (getPestanaActiva()) {
            case 0 -> destruirCliente();
            case 1 -> destruirConductor();
            case 2 -> destruirAdministrador();
            case 3 -> destruirVehiculo();
            case 4 -> destruirTarifa();
        }
    }

    private void crearCliente() {
        try {
            if (objCliente != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un cliente. Destruyalo antes de crear uno nuevo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String curp = jTextField1.getText();
            String nombres = jTextField2.getText();
            String apellidos = jTextField3.getText();
            String edadStr = jTextField4.getText().trim();
            String telefono = jTextField5.getText();
            if (edadStr.isEmpty()) throw new IllegalArgumentException("La edad no puede estar vacia.");
            int edad = Integer.parseInt(edadStr);
            objCliente = new front_end.Cliente(curp, nombres, apellidos, edad, telefono);
            jTextArea1.setText("Cliente creado exitosamente.\n" + objCliente.toString());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "La edad debe ser un numero entero valido.", "Error de tipo", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarCliente() {
        String curp = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el CURP a buscar:", "Buscar Cliente", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (curp == null) return;
        curp = curp.trim().toUpperCase();
        if (curp.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El CURP no puede estar vacio.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objCliente != null && objCliente.getCurp().equals(curp)) {
            jTextArea1.setText("Cliente encontrado.\n" + objCliente.toString());
        } else {
            jTextArea1.setText("No existe un cliente con CURP: " + curp);
        }
    }

    private void mostrarCliente() {
        jTextArea1.setText(objCliente == null ? "No existe un cliente actualmente." : objCliente.toString());
    }

    private void actualizarCliente() {
        try {
            if (objCliente == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No existe un cliente para actualizar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String nombres = jTextField2.getText();
            String apellidos = jTextField3.getText();
            String edadStr = jTextField4.getText().trim();
            String telefono = jTextField5.getText();
            if (!nombres.trim().isEmpty()) objCliente.setNombres(nombres);
            if (!apellidos.trim().isEmpty()) objCliente.setApellidos(apellidos);
            if (!edadStr.isEmpty()) objCliente.setEdad(Integer.parseInt(edadStr));
            if (!telefono.trim().isEmpty()) objCliente.setTelefono(telefono);
            jTextArea1.setText("Cliente actualizado.\n" + objCliente.toString());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "La edad debe ser un numero entero valido.", "Error de tipo", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void borrarCliente() {
        if (objCliente == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe un cliente para borrar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se borraran los datos del cliente. Confirmar?", "Borrar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objCliente.setNombres("(borrado)");
            objCliente.setApellidos("(borrado)");
            objCliente.setTelefono("0000000000");
            objCliente.setEstado("Inactivo");
            limpiarCamposCliente();
            jTextArea1.setText("Datos del cliente borrados. La referencia sigue activa.\n" + objCliente.toString());
        }
    }

    private void destruirCliente() {
        if (objCliente == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe un cliente para destruir.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se eliminara la referencia al cliente. Esta accion no se puede deshacer. Confirmar?", "Destruir", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objCliente = null;
            limpiarCamposCliente();
            jTextArea1.setText("Referencia al cliente destruida. Ya no existe en la aplicacion.");
        }
    }

    private void limpiarCamposCliente() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }

    private void crearConductor() {
        try {
            if (objConductor != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un conductor. Destruyalo antes de crear uno nuevo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String curp = jTextField6.getText();
            String nomCompleto = jTextField7.getText();
            String numLicencia = jTextField8.getText();
            String placas = jTextField9.getText();
            String edadStr = jTextField10.getText().trim();
            if (edadStr.isEmpty()) throw new IllegalArgumentException("La edad no puede estar vacia.");
            int edad = Integer.parseInt(edadStr);
            objConductor = new front_end.Conductor(curp, nomCompleto, numLicencia, placas, edad);
            jTextArea1.setText("Conductor creado exitosamente.\n" + objConductor.toString());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "La edad debe ser un numero entero valido.", "Error de tipo", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarConductor() {
        String curp = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el CURP a buscar:", "Buscar Conductor", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (curp == null) return;
        curp = curp.trim().toUpperCase();
        if (curp.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El CURP no puede estar vacio.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objConductor != null && objConductor.getCurp().equals(curp)) {
            jTextArea1.setText("Conductor encontrado.\n" + objConductor.toString());
        } else {
            jTextArea1.setText("No existe un conductor con CURP: " + curp);
        }
    }

    private void mostrarConductor() {
        jTextArea1.setText(objConductor == null ? "No existe un conductor actualmente." : objConductor.toString());
    }

    private void actualizarConductor() {
        try {
            if (objConductor == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No existe un conductor para actualizar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String nomCompleto = jTextField7.getText();
            String numLicencia = jTextField8.getText();
            String placas = jTextField9.getText();
            String edadStr = jTextField10.getText().trim();
            if (!nomCompleto.trim().isEmpty()) objConductor.setNomCompleto(nomCompleto);
            if (!numLicencia.trim().isEmpty()) objConductor.setNumLicencia(numLicencia);
            if (!placas.trim().isEmpty()) objConductor.setPlacas(placas);
            if (!edadStr.isEmpty()) objConductor.setEdad(Integer.parseInt(edadStr));
            jTextArea1.setText("Conductor actualizado.\n" + objConductor.toString());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "La edad debe ser un numero entero valido.", "Error de tipo", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void borrarConductor() {
        if (objConductor == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe un conductor para borrar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se borraran los datos del conductor. Confirmar?", "Borrar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objConductor.setNomCompleto("(borrado)");
            objConductor.setNumLicencia("000000");
            objConductor.setPlacas("AAA000");
            objConductor.setEstado("Inactivo");
            limpiarCamposConductor();
            jTextArea1.setText("Datos del conductor borrados. La referencia sigue activa.\n" + objConductor.toString());
        }
    }

    private void destruirConductor() {
        if (objConductor == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe un conductor para destruir.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se eliminara la referencia al conductor. Confirmar?", "Destruir", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objConductor = null;
            limpiarCamposConductor();
            jTextArea1.setText("Referencia al conductor destruida. Ya no existe en la aplicacion.");
        }
    }

    private void limpiarCamposConductor() {
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
    }

    private void crearAdministrador() {
        try {
            if (objAdministrador != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un administrador. Destruyalo antes de crear uno nuevo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String curp = jTextField11.getText();
            String nombres = jTextField12.getText();
            String apellidos = jTextField13.getText();
            String numEmpleado = jTextField14.getText();
            String turno = (String) jComboBox1.getSelectedItem();
            objAdministrador = new front_end.Administrador(curp, nombres, apellidos, numEmpleado, turno);
            jTextArea1.setText("Administrador creado exitosamente.\n" + objAdministrador.toString());
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarAdministrador() {
        String curp = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el CURP a buscar:", "Buscar Administrador", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (curp == null) return;
        curp = curp.trim().toUpperCase();
        if (curp.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El CURP no puede estar vacio.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objAdministrador != null && objAdministrador.getCurp().equals(curp)) {
            jTextArea1.setText("Administrador encontrado.\n" + objAdministrador.toString());
        } else {
            jTextArea1.setText("No existe un administrador con CURP: " + curp);
        }
    }

    private void mostrarAdministrador() {
        jTextArea1.setText(objAdministrador == null ? "No existe un administrador actualmente." : objAdministrador.toString());
    }

    private void actualizarAdministrador() {
        try {
            if (objAdministrador == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No existe un administrador para actualizar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String nombres = jTextField12.getText();
            String apellidos = jTextField13.getText();
            String numEmpleado = jTextField14.getText();
            String turno = (String) jComboBox1.getSelectedItem();
            if (!nombres.trim().isEmpty()) objAdministrador.setNombres(nombres);
            if (!apellidos.trim().isEmpty()) objAdministrador.setApellidos(apellidos);
            if (!numEmpleado.trim().isEmpty()) objAdministrador.setNumEmpleado(numEmpleado);
            if (!turno.equals("-")) objAdministrador.setTurno(turno);
            jTextArea1.setText("Administrador actualizado.\n" + objAdministrador.toString());
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void borrarAdministrador() {
        if (objAdministrador == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe un administrador para borrar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se borraran los datos del administrador. Confirmar?", "Borrar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objAdministrador.setNombres("(borrado)");
            objAdministrador.setApellidos("(borrado)");
            objAdministrador.setNumEmpleado("000");
            objAdministrador.setEstado("Inactivo");
            limpiarCamposAdministrador();
            jTextArea1.setText("Datos del administrador borrados. La referencia sigue activa.\n" + objAdministrador.toString());
        }
    }

    private void destruirAdministrador() {
        if (objAdministrador == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe un administrador para destruir.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se eliminara la referencia al administrador. Confirmar?", "Destruir", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objAdministrador = null;
            limpiarCamposAdministrador();
            jTextArea1.setText("Referencia al administrador destruida. Ya no existe en la aplicacion.");
        }
    }

    private void limpiarCamposAdministrador() {
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jComboBox1.setSelectedIndex(0);
    }

    private void crearVehiculo() {
        try {
            if (objVehiculo != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ya existe un vehiculo. Destruyalo antes de crear uno nuevo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String placas = jTextField15.getText();
            String marca = jTextField16.getText();
            String modelo = jTextField17.getText();
            String anioStr = jTextField18.getText().trim();
            String color = jTextField19.getText();
            if (anioStr.isEmpty()) throw new IllegalArgumentException("El anio no puede estar vacio.");
            int anio = Integer.parseInt(anioStr);
            objVehiculo = new front_end.Vehiculo(placas, marca, modelo, anio, color);
            jTextArea1.setText("Vehiculo creado exitosamente.\n" + objVehiculo.toString());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "El anio debe ser un numero entero valido.", "Error de tipo", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarVehiculo() {
        String placas = javax.swing.JOptionPane.showInputDialog(this, "Ingrese las Placas a buscar:", "Buscar Vehiculo", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (placas == null) return;
        placas = placas.trim().toUpperCase();
        if (placas.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Las placas no pueden estar vacias.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objVehiculo != null && objVehiculo.getPlacas().equals(placas)) {
            jTextArea1.setText("Vehiculo encontrado.\n" + objVehiculo.toString());
        } else {
            jTextArea1.setText("No existe un vehiculo con placas: " + placas);
        }
    }

    private void mostrarVehiculo() {
        jTextArea1.setText(objVehiculo == null ? "No existe un vehiculo actualmente." : objVehiculo.toString());
    }

    private void actualizarVehiculo() {
        try {
            if (objVehiculo == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No existe un vehiculo para actualizar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String marca = jTextField16.getText();
            String modelo = jTextField17.getText();
            String anioStr = jTextField18.getText().trim();
            String color = jTextField19.getText();
            if (!marca.trim().isEmpty()) objVehiculo.setMarca(marca);
            if (!modelo.trim().isEmpty()) objVehiculo.setModelo(modelo);
            if (!anioStr.isEmpty()) objVehiculo.setAnio(Integer.parseInt(anioStr));
            if (!color.trim().isEmpty()) objVehiculo.setColor(color);
            jTextArea1.setText("Vehiculo actualizado.\n" + objVehiculo.toString());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "El anio debe ser un numero entero valido.", "Error de tipo", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void borrarVehiculo() {
        if (objVehiculo == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe un vehiculo para borrar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se borraran los datos del vehiculo. Confirmar?", "Borrar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objVehiculo.setMarca("(borrado)");
            objVehiculo.setModelo("(borrado)");
            objVehiculo.setColor("(borrado)");
            objVehiculo.setEstado("Inactivo");
            limpiarCamposVehiculo();
            jTextArea1.setText("Datos del vehiculo borrados. La referencia sigue activa.\n" + objVehiculo.toString());
        }
    }

    private void destruirVehiculo() {
        if (objVehiculo == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe un vehiculo para destruir.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se eliminara la referencia al vehiculo. Confirmar?", "Destruir", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objVehiculo = null;
            limpiarCamposVehiculo();
            jTextArea1.setText("Referencia al vehiculo destruida. Ya no existe en la aplicacion.");
        }
    }

    private void limpiarCamposVehiculo() {
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
    }

    private void crearTarifa() {
        try {
            if (objTarifa != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ya existe una tarifa. Destruyala antes de crear una nueva.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String tipoServicio = (String) jComboBox2.getSelectedItem();
            String codigo = jTextField20.getText();
            String minutosStr = jTextField21.getText().trim();
            String precioKMStr = jTextField22.getText().trim();
            String costoStr = jTextField23.getText().trim();
            if (minutosStr.isEmpty()) throw new IllegalArgumentException("Los minutos no pueden estar vacios.");
            if (precioKMStr.isEmpty()) throw new IllegalArgumentException("El precio K/M no puede estar vacio.");
            if (costoStr.isEmpty()) throw new IllegalArgumentException("El costo no puede estar vacio.");
            int minutos = Integer.parseInt(minutosStr);
            double precioKM = Double.parseDouble(precioKMStr);
            double costo = Double.parseDouble(costoStr);
            objTarifa = new front_end.Tarifa(tipoServicio, codigo, minutos, precioKM, costo);
            jTextArea1.setText("Tarifa creada exitosamente.\n" + objTarifa.toString());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Minutos, Precio K/M y Costo deben ser valores numericos validos.", "Error de tipo", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarTarifa() {
        String codigo = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el Codigo a buscar:", "Buscar Tarifa", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (codigo == null) return;
        codigo = codigo.trim().toUpperCase();
        if (codigo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El codigo no puede estar vacio.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (objTarifa != null && objTarifa.getCodigo().equals(codigo)) {
            jTextArea1.setText("Tarifa encontrada.\n" + objTarifa.toString());
        } else {
            jTextArea1.setText("No existe una tarifa con codigo: " + codigo);
        }
    }

    private void mostrarTarifa() {
        jTextArea1.setText(objTarifa == null ? "No existe una tarifa actualmente." : objTarifa.toString());
    }

    private void actualizarTarifa() {
        try {
            if (objTarifa == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No existe una tarifa para actualizar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            String tipoServicio = (String) jComboBox2.getSelectedItem();
            String minutosStr = jTextField21.getText().trim();
            String precioKMStr = jTextField22.getText().trim();
            String costoStr = jTextField23.getText().trim();
            if (!tipoServicio.equals("-")) objTarifa.setTipoServicio(tipoServicio);
            if (!minutosStr.isEmpty()) objTarifa.setMinutos(Integer.parseInt(minutosStr));
            if (!precioKMStr.isEmpty()) objTarifa.setPrecioKM(Double.parseDouble(precioKMStr));
            if (!costoStr.isEmpty()) objTarifa.setCosto(Double.parseDouble(costoStr));
            jTextArea1.setText("Tarifa actualizada.\n" + objTarifa.toString());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Minutos, Precio K/M y Costo deben ser valores numericos validos.", "Error de tipo", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de validacion", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void borrarTarifa() {
        if (objTarifa == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe una tarifa para borrar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se borraran los datos de la tarifa. Confirmar?", "Borrar", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objTarifa.setMinutos(1);
            objTarifa.setPrecioKM(0.01);
            objTarifa.setCosto(0);
            objTarifa.setEstado("Inactivo");
            limpiarCamposTarifa();
            jTextArea1.setText("Datos de la tarifa borrados. La referencia sigue activa.\n" + objTarifa.toString());
        }
    }

    private void destruirTarifa() {
        if (objTarifa == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe una tarifa para destruir.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int r = javax.swing.JOptionPane.showConfirmDialog(this, "Se eliminara la referencia a la tarifa. Confirmar?", "Destruir", javax.swing.JOptionPane.YES_NO_OPTION);
        if (r == javax.swing.JOptionPane.YES_OPTION) {
            objTarifa = null;
            limpiarCamposTarifa();
            jTextArea1.setText("Referencia a la tarifa destruida. Ya no existe en la aplicacion.");
        }
    }

    private void limpiarCamposTarifa() {
        jComboBox2.setSelectedIndex(0);
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
